### ISSUE TITLE
Sorting Alphabetically

### ISSUE THREAD

**Issue by dmgm** [ABJC/ABJC-Issues#10]
I'm testing ABJC [Beta 1.0.0 (13)] and finding navigation of TV shows awkward.

I'd like to have an option to display the Movies or TV Series arranged alphabetically, or perhaps toggled through different groupings. While I like the grouping by Action, Adventure etc, it's not as practical as scrolling through to B, to find Big Bang Theory. 

Once a show is found and clicked into, the interface is excellent. although I will also report the episodes don't play.
Episodes don't appear to play from the Season Grouping. I can select them but they do not play. They do play from the continue button, movies and watch now continue shows also play.

**Comment by NoahKamara** [comment]
Hey there,
What would you think about an alphabetical list in the search view? So when you don't enter a query you get all items listed alphabetically (grouped).

A click on the  episode row should only select the current episode. You still have to click on "continue" to play. This is so you can read the episodes info.

**Comment by NoahKamara** [comment]
Hey again,
I've implemented an alphabetical library view in the latest build.
Any chance you already looked at it? When you do feel free to give me feedback 😄

**Comment by NoahKamara** [comment]
Hey again,
The latest build contains an option to sort your library by genre, title, release year & decade
