### ISSUE TITLE
App crashing when trying to play .mp4 file

### ISSUE THREAD

**Issue by aumeh** [ABJC/ABJC-Issues#12]
TVOS version: 14.4 (apple tv 4th I believe)
ABJC version: Latest (downloaded minutes ago)
Jellyfin Version: Latest stable (10.7.0)
detailed steps to reproduce the bug: Attempting to watch a .mp4 video file format and when trying to open the episode of the tv show it crashes the app and takes me back to the apple tv main screen. I was doing this to counter inFuze and how it does not allow me to play .mp4 file formats without going to pro (not looking to do that hence jellyfin). Any suggestions or tips on my end let me know. thanks

**Comment by TheNamelessWonderer** [comment]
I have the same issue but this happens for all formats regardless of what I play. Most likely an issue with 10.7 and the app.

**Comment by NoahKamara** [comment]
Hey there,
thanks for the bug report. I'll update my server and check it out

**Comment by NoahKamara** [comment]
I'm merging all issues regarding playback into one. Seems like media source selection logic needs improvement 
https://github.com/ABJC/ABJC-Issues/issues/6
