### ISSUE TITLE
[BUG] Login information not saved

### ISSUE THREAD

**Issue by TheNamelessWonderer** [ABJC/ABJC-Issues#13]
**Describe the bug**
Login and server information not saved.

**To Reproduce**
1. Sign in
2. Force close app
3. Reopen app

**Expected behavior**
The server and login information should be saved. 

**Device & Version:**
 - tvOS Version: 14.4
 - ABJC Version: 1.0.0
 - ABJC Build: 16

**Additional context**
Running Jellyfin 10.7 with https and a reverse proxy.

**Comment by NoahKamara** [comment]
Hey there,
I uploaded a new build yesterday with improved credentials saving logic. Have you had a change to try it out yet?

**Comment by TheNamelessWonderer** [comment]
Yep it works now! Thank you.
