### ISSUE TITLE
[BUG] TV Shows not working and crashing app

### ISSUE THREAD

**Issue by TheNamelessWonderer** [ABJC/ABJC-Issues#15]
**Describe the bug**
If you try to play a TV Show the app crashes.

**To Reproduce**
1. Select a TV Show
2. Click continue
3. See app crash

**Expected behavior**
The TV Show should play without any errors.

**Device & Version:**
 - tvOS Version: 14.5
 - ABJC Version 1.0.0
 - ABJC Build 20

**Comment by NoahKamara** [comment]
Hey,
Thanks for the bug report. 

Is it with any tv show or only a specific one? 
is an episode selected (the detail page should show episode and season number below the title)?
can you try manually selecting an episode below and then press continue?

**Comment by petitbou0169** [comment]
Hello,

I confirm that when you select an episode and play, sometimes the application crashes.
Another bug is that once the episode is launched, if you come back with the menu and want to launch another series or a movie, it restarts the episode of the series you selected before. We are obliged to restart the apple tv

**Comment by NoahKamara** [comment]
I'm merging all issues regarding playback into one. Seems like media source selection logic needs improvement 
https://github.com/ABJC/ABJC-Issues/issues/6
