### ISSUE TITLE
"No Username specified"

### ISSUE THREAD

**Issue by NolanWelser** [ABJC/ABJC-Issues#3]
When I attempt to login by using the servers IP address I have no issues, but if I use my public facing domain name with HTTPS, even when I have a user/pass filled out I get an authentication error that I have not specified a username

**Comment by NoahKamara** [comment]
Hey,
can you enable Debug Mode by long pressing the "Manual Entry" Button?
It should enable more detailed error messages.

**Comment by NolanWelser** [comment]
"trying to authenticate [user]@[domain.com]:443 resulted in badRequest"
HTTPS is set to ON, and I did NOT include "https://" in the host/domain name

**Comment by NoahKamara** [comment]
The current build (15) should fix issues regarding to HTTPS.
all problems with https are tracked [here](https://github.com/ABJC/ABJC-Issues/issues/9)
