### ISSUE TITLE
Sign in error: Wrong IP or port

### ISSUE THREAD

**Issue by halpcomputar** [ABJC/ABJC-Issues#4]
The application is able to autodiscover the jellyfin server (running on ubuntu server 20.04), but when I try to sign in with credentials from any account, it claims the IP address or port is incorrect. Same behavior observed if manually entering the correct port and IP address.

From the jellyfin server, I can pull logs and see that the user is authenticating, according to Jellyfin, but ABJC gives error upon login attempt.

**Comment by AlfHou** [comment]
My server is located behind a reverse proxy which uses HTTPS

**Comment by NoahKamara** [comment]
Does your server use the default port? And does it use a path (e.g. XXX.XXX.XXX.XXX:PORT/path/to/server)

**Comment by AlfHou** [comment]
It is reached through the revere proxy with jellyfin.{mydomain}.com, and since it uses https it connects on port 443.
Behind the reverse proxy, it is forwarded to xxx.xxx.xxx.xxx:8096

**Comment by NoahKamara** [comment]
Ok. Did you specify 443 as port?
With Debug Mode enabled (long pressing “Manual Entry”-Button will enable it), what is the error?
Does it maybe try to connect to a different address?

**Comment by AlfHou** [comment]
Hmm. I don't really remember, but I think I tried a lot of different options. Unfortunately I'm away form my appleTV until after christmas. I will test it again then.

**Comment by rasmuslos** [comment]
I get an 404 not Found error. Using 10.7.0

**Comment by NoahKamara** [comment]
I found an issue with HTTPS and fixed it in the build that went online today.
Issues with HTTPS are tracked [here](https://github.com/ABJC/ABJC-Issues/issues/9)
