### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by jaredmoody** [ABJC/ABJC-Issues#7]
When I scroll through media to the right on Watch Now, when I reach the end, I can't scroll back.

Similarly, if I scroll down under "Movies", when I reach the end, I can't scroll back up.

**Comment by NoahKamara** [comment]
Can you try to scroll all the way to the left of the row at the bottom and scroll up from there?
The app still has some problems with Focus Engine, which coordinates navigation with the atv remote. Apple unfortunately hasn't implemented all of the APIs in SwiftUI but I'm working on a solution

**Comment by jaredmoody** [comment]
No, the whole screen is stuck - the selected item is changing but nothing scrolls into view

**Comment by NoahKamara** [comment]
Hey,
the latest build contains some performance optimizations which should reduce stuttering.
Does the problem still persist?

**Comment by jaredmoody** [comment]
This is overall worse on the latest build. I can't scroll in any direction now.
