### ISSUE TITLE
HTTPS Not Working

### ISSUE THREAD

**Issue by evanreichard** [ABJC/ABJC-Issues#9]
I set hostname (no "https://", just "sub1.sub2.example.com") and port (443) then set "HTTPS" to on.

When attempting to sign on, it errors with "Authentication Failure - Wrong Server Adress or Port" (also side note: "Adress" is misspelled)

**Comment by NoahKamara** [comment]
The issue should be fixed in the current build (15)
The issue occurred because the option to use HTTPS was not properly saved
